export class BaseHealthyUrlConstant {
 public static readonly BASE_HEALTHY_MEDICINE_V1_ADD: string = 'base-healthy/base/healthy/medicine/v1/add';
 public static readonly BASE_HEALTHY_MEDICINE_V1_BATCH_ADD: string = 'base-healthy/base/healthy/medicine/v1/batchAdd';
 public static readonly BASE_HEALTHY_MEDICINE_V1_DELETE: string = 'base-healthy/base/healthy/medicine/v1/delete';
 public static readonly BASE_HEALTHY_MEDICINE_V1_FINISH: string = 'base-healthy/base/healthy/medicine/v1/finish';
 public static readonly BASE_HEALTHY_MEDICINE_V1_GET_HOME_PAGE: string = 'base-healthy/base/healthy/medicine/v1/getHomePage';
 public static readonly BASE_HEALTHY_MEDICINE_V1_INFO: string = 'base-healthy/base/healthy/medicine/v1/info';
 public static readonly BASE_HEALTHY_MEDICINE_V1_MEDICINE_DELAY_REMIND_ADD_OR_UPDATE: string = 'base-healthy/base/healthy/medicine/v1/medicineDelayRemindAddOrUpdate';
 public static readonly BASE_HEALTHY_MEDICINE_V1_MEDICINE_DELAY_REMIND_INFO: string = 'base-healthy/base/healthy/medicine/v1/medicineDelayRemindInfo';
 public static readonly BASE_HEALTHY_MEDICINE_V1_MEDICINE_LIST: string = 'base-healthy/base/healthy/medicine/v1/medicineList';
 public static readonly BASE_HEALTHY_MEDICINE_V1_MEDICINE_TEMPLATE: string = 'base-healthy/base/healthy/medicine/v1/medicineTemplate';
 public static readonly BASE_HEALTHY_MEDICINE_V1_SEARCH: string = 'base-healthy/base/healthy/medicine/v1/search';
 public static readonly BASE_HEALTHY_MEDICINE_V1_SORT: string = 'base-healthy/base/healthy/medicine/v1/sort';
 public static readonly BASE_HEALTHY_MEDICINE_V1_SWITCH_PUSH: string = 'base-healthy/base/healthy/medicine/v1/switchPush';
 public static readonly BASE_HEALTHY_MEDICINE_V1_SYNC_DATA: string = 'base-healthy/base/healthy/medicine/v1/syncData';
 public static readonly BASE_HEALTHY_MEDICINE_V1_SYNC_FINISHED_DATA: string = 'base-healthy/base/healthy/medicine/v1/syncFinishedData';
 public static readonly BASE_HEALTHY_MEDICINE_V1_UPDATE: string = 'base-healthy/base/healthy/medicine/v1/update';
 public static readonly BASE_MEDICINE_V1_GET_MEDICINE_ID: string = 'base-healthy/base/medicine/v1/getMedicineId';
 public static readonly BASE_MEDICINE_V1_MY_APPLET: string = 'base-healthy/base/medicine/v1/myApplet';
 public static readonly BASE_MEDICINE_V1_SELECT_BY_IDS_URL: string = 'base-healthy/base/medicine/v1/select-by-ids';
 public static readonly BASE_MEDICINE_V1_SHORTCUT_APPLET: string = 'base-healthy/base/medicine/v1/shortcutApplet';
 public static readonly BASE_MEDICINE_V1_TODO_VIEW_LIST: string = 'base-healthy/base/medicine/v1/todoViewList';
 public static readonly CHECKALIVE: string = 'base-healthy/checkalive';
}
