export class BaseMedalUrlConstant {
 public static readonly BASE_MEDAL_MEMORIAL_BOOK_V1_DETAIL: string = 'base-medal/base/medal/memorial/book/v1/detail';
 public static readonly BASE_MEDAL_MEMORIAL_BOOK_V1_HALL_YEAR: string = 'base-medal/base/medal/memorial/book/v1/hall/year';
 public static readonly BASE_MEDAL_MEMORIAL_BOOK_V1_HIDE_PAGE: string = 'base-medal/base/medal/memorial/book/v1/hidePage';
 public static readonly BASE_MEDAL_MEMORIAL_BOOK_V1_SHARE_DETAIL: string = 'base-medal/base/medal/memorial/book/v1/shareDetail';
 public static readonly BASE_MEDAL_MEMORIAL_BOOK_V1_START_PAGE: string = 'base-medal/base/medal/memorial/book/v1/startPage';
 public static readonly BASE_MEDAL_V1_ACHIEVEMENT_REACH_DISPLAY: string = 'base-medal/base/medal/v1/achievement/reach/display';
 public static readonly BASE_MEDAL_V1_ACHIEVEMENT_REACH_LIST: string = 'base-medal/base/medal/v1/achievement/reach/list';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_ADD: string = 'base-medal/base/medal/v1/dailySummary/add';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_ARCHIVE_STATUS: string = 'base-medal/base/medal/v1/dailySummary/archiveStatus';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_GET: string = 'base-medal/base/medal/v1/dailySummary/get';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_GET_DATA_BY_APPLET_ID: string = 'base-medal/base/medal/v1/dailySummary/getDataByAppletId';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_GET_STATISTICS: string = 'base-medal/base/medal/v1/dailySummary/getStatistics';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_SEARCH: string = 'base-medal/base/medal/v1/dailySummary/search';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_UPDATE: string = 'base-medal/base/medal/v1/dailySummary/update';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_UPDATE_USER_DATA: string = 'base-medal/base/medal/v1/dailySummary/updateUserData';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_TEMPLATE_GET: string = 'base-medal/base/medal/v1/dailySummaryTemplate/get';
 public static readonly BASE_MEDAL_V1_DAILY_SUMMARY_TEMPLATE_UPDATE: string = 'base-medal/base/medal/v1/dailySummaryTemplate/update';
 public static readonly BASE_MEDAL_V1_HOMEPAGE: string = 'base-medal/base/medal/v1/homepage';
 public static readonly BASE_MEDAL_V1_IP_HOUSE_ACTIVITY_LIST: string = 'base-medal/base/medal/v1/ipHouseActivity/list';
 public static readonly BASE_MEDAL_V1_SYNC_GUESS_DO_BASE_RECORD: string = 'base-medal/base/medal/v1/sync/guessDoBaseRecord';
 public static readonly BASE_MEDAL_V1_USER_CUSTOM_ADD: string = 'base-medal/base/medal/v1/userCustom/add';
 public static readonly BASE_MEDAL_V1_USER_CUSTOM_CHECK_HISTORY_DATA: string = 'base-medal/base/medal/v1/userCustom/checkHistoryData';
 public static readonly BASE_MEDAL_V1_USER_CUSTOM_DELETE: string = 'base-medal/base/medal/v1/userCustom/delete';
 public static readonly BASE_MEDAL_V1_USER_CUSTOM_UPDATE: string = 'base-medal/base/medal/v1/userCustom/update';
 public static readonly CHECKALIVE: string = 'base-medal/checkalive';
}
