export class BaseRunUrlConstant {
 public static readonly BASE_RUN_V1_FINISH: string = 'base-run/base/run/v1/finish';
 public static readonly BASE_RUN_V1_GET_RUN_PERSONAL_RECORD: string = 'base-run/base/run/v1/getRunPersonalRecord';
 public static readonly BASE_RUN_V1_GET_RUN_RECORD: string = 'base-run/base/run/v1/getRunRecord';
 public static readonly BASE_RUN_V1_GET_RUN_RECORD_BY_DAY: string = 'base-run/base/run/v1/getRunRecordByDay';
 public static readonly BASE_RUN_V1_GET_RUN_RECORD_BY_YEAR: string = 'base-run/base/run/v1/getRunRecordByYear';
 public static readonly BASE_RUN_V1_GET_RUN_RECORDS: string = 'base-run/base/run/v1/getRunRecords';
 public static readonly BASE_RUN_V1_GET_RUN_REMIND_CONFIG: string = 'base-run/base/run/v1/getRunRemindConfig';
 public static readonly BASE_RUN_V1_INIT_RUN: string = 'base-run/base/run/v1/initRun';
 public static readonly BASE_RUN_V1_SAVE_RUN_NOTES: string = 'base-run/base/run/v1/saveRunNotes';
 public static readonly BASE_RUN_V1_SAVE_RUN_RECORD: string = 'base-run/base/run/v1/saveRunRecord';
 public static readonly BASE_RUN_V1_SAVE_RUN_REMIND: string = 'base-run/base/run/v1/saveRunRemind';
 public static readonly BASE_RUN_V1_SAVE_RUN_TARGET: string = 'base-run/base/run/v1/saveRunTarget';
 public static readonly BASE_RUN_V1_SAVE_RUN_VOICE_TIPS: string = 'base-run/base/run/v1/saveRunVoiceTips';
 public static readonly BASE_RUN_V1_SYNC_DATA_URL: string = 'base-run/base/run/v1/sync_data';
 public static readonly BASE_RUN_V1_SYNC_FINISHED_DATA_URL: string = 'base-run/base/run/v1/sync_finished_data';
 public static readonly BASE_RUN_V1_TODO_VIEW_LIST_URL: string = 'base-run/base/run/v1/todo_view_list';
 public static readonly CHECKALIVE: string = 'base-run/checkalive';
}
