export class BaseEncyclopediasUrlConstant {
 public static readonly BASE_ENCYCLOPEDIAS_V1_ADD_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v1/addUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V1_DEL_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v1/delUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V1_GET_JBXX: string = 'base-encyclopedias/base/encyclopedias/v1/getJbxx';
 public static readonly BASE_ENCYCLOPEDIAS_V1_GET_USER_ALL_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v1/getUserAllEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V1_GET_USER_ENCYCLOPEDIAS_LIST: string = 'base-encyclopedias/base/encyclopedias/v1/getUserEncyclopediasList';
 public static readonly BASE_ENCYCLOPEDIAS_V1_GET_USER_LIFE_TRACK: string = 'base-encyclopedias/base/encyclopedias/v1/getUserLifeTrack';
 public static readonly BASE_ENCYCLOPEDIAS_V1_SAVE_PERSONAL_COMMENT: string = 'base-encyclopedias/base/encyclopedias/v1/savePersonalComment';
 public static readonly BASE_ENCYCLOPEDIAS_V1_SORT_COMMENT: string = 'base-encyclopedias/base/encyclopedias/v1/sortComment';
 public static readonly BASE_ENCYCLOPEDIAS_V1_UPDATE_COMMENT_SORT: string = 'base-encyclopedias/base/encyclopedias/v1/updateCommentSort';
 public static readonly BASE_ENCYCLOPEDIAS_V1_UPDATE_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v1/updateUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V2_ADD_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v2/addUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V2_DEL_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v2/delUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V2_GET_USER_ALL_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v2/getUserAllEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V2_GET_USER_ENCYCLOPEDIAS_LIST: string = 'base-encyclopedias/base/encyclopedias/v2/getUserEncyclopediasList';
 public static readonly BASE_ENCYCLOPEDIAS_V2_UPDATE_USER_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v2/updateUserEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V3_GET_USER_ALL_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v3/getUserAllEncyclopedias';
 public static readonly BASE_ENCYCLOPEDIAS_V4_GET_USER_ALL_ENCYCLOPEDIAS: string = 'base-encyclopedias/base/encyclopedias/v4/getUserAllEncyclopedias';
 public static readonly CHECKALIVE: string = 'base-encyclopedias/checkalive';
}
