export class BaseCallbackUrlConstant {
 public static readonly BASE_CALLBACK_V1_AD: string = 'base-callback/base/callback/v1/ad';
 public static readonly BASE_CALLBACK_V1_GDT_AUTHCODE: string = 'base-callback/base/callback/v1/gdt/authcode';
 public static readonly BASE_CALLBACK_V1_GET_URL: string = 'base-callback/base/callback/v1/getUrl';
 public static readonly BASE_CALLBACK_V1_IOS_ATTRIBUTION: string = 'base-callback/base/callback/v1/ios/attribution';
 public static readonly BASE_CALLBACK_V1_IOS_ERROR_ATTRIBUTION: string = 'base-callback/base/callback/v1/ios/error/attribution';
 public static readonly BASE_CALLBACK_V1_IOS_REPORT: string = 'base-callback/base/callback/v1/ios/report';
 public static readonly BASE_CALLBACK_V1_IOS_SYNC: string = 'base-callback/base/callback/v1/ios/sync';
 public static readonly BASE_CALLBACK_V1_VIVO: string = 'base-callback/base/callback/v1/vivo';
 public static readonly BASE_CALLBACK_V1_VIVO_MKT_URL: string = 'base-callback/base/callback/v1/vivo_mkt';
 public static readonly BASE_CALLBACK_V1_WALL_CLICK: string = 'base-callback/base/callback/v1/wall/click';
 public static readonly BASE_CALLBACK_V1_WALL_IS_ACTIVE: string = 'base-callback/base/callback/v1/wall/isActive';
 public static readonly BASE_CALLBACK_V2_WALL_IS_ACTIVE: string = 'base-callback/base/callback/v2/wall/isActive';
 public static readonly CHECKALIVE: string = 'base-callback/checkalive';
}
