export class BaseChatUrlConstant {
 public static readonly BASE_CHAT_V1_DRAW: string = 'base-chat/base/chat/v1/draw';
 public static readonly BASE_CHAT_V1_DRAW_HISTORY: string = 'base-chat/base/chat/v1/draw/history';
 public static readonly BASE_CHAT_V1_MESSAGE_DELETE: string = 'base-chat/base/chat/v1/message/delete';
 public static readonly BASE_CHAT_V1_MESSAGE_DETAIL: string = 'base-chat/base/chat/v1/message/detail';
 public static readonly BASE_CHAT_V1_MESSAGE_LIST: string = 'base-chat/base/chat/v1/message/list';
 public static readonly BASE_CHAT_V1_MESSAGE_PARSE_INTENTION: string = 'base-chat/base/chat/v1/message/parseIntention';
 public static readonly BASE_CHAT_V1_MESSAGE_POLISH: string = 'base-chat/base/chat/v1/message/polish';
 public static readonly BASE_CHAT_V1_MESSAGE_SYNC: string = 'base-chat/base/chat/v1/message/sync';
 public static readonly BASE_CHAT_V1_MESSAGE_UPDATE_XIAOXU_MESSAGE: string = 'base-chat/base/chat/v1/message/updateXiaoxuMessage';
 public static readonly BASE_CHAT_V1_USE_COUNT_OPENAI_TIP: string = 'base-chat/base/chat/v1/use/count/openaiTip';
 public static readonly BASE_CHAT_V1_USE_COUNT_XIAOXU_TIP: string = 'base-chat/base/chat/v1/use/count/xiaoxuTip';
 public static readonly CHECKALIVE: string = 'base-chat/checkalive';
 public static readonly BASE_CHAT_V2_MESSAGE_QUESTION: string = 'base/chat/v2/message/question';
}
