export class BaseRemindUrlConstant {
 public static readonly BASE_REMIND_BATCH_PUSH: string = 'base-remind/base/remind/batchPush';
 public static readonly BASE_REMIND_PUSH: string = 'base-remind/base/remind/push';
 public static readonly BASE_REMIND_PUSH_BATCH_REMIND_NO_CHECK_SWITCH: string = 'base-remind/base/remind/pushBatchRemindNoCheckSwitch';
 public static readonly BASE_REMIND_TRIGGER_REMIND_URL: string = 'base-remind/base/remind/trigger-remind';
 public static readonly CHECKALIVE: string = 'base-remind/checkalive';
}
