export class BaseLifedayUrlConstant {
 public static readonly BASE_LIFEDAY_SYNC_DATA_URL: string = 'base-lifeday/base/lifeday/sync_data';
 public static readonly BASE_LIFEDAY_V1_DATE_RANGE_COUNT: string = 'base-lifeday/base/lifeday/v1/dateRangeCount';
 public static readonly BASE_LIFEDAY_V1_GET_LIFE_DAY: string = 'base-lifeday/base/lifeday/v1/getLifeDay';
 public static readonly BASE_LIFEDAY_V1_GET_LIFEDAY_GUIDE_TEMPLATE: string = 'base-lifeday/base/lifeday/v1/getLifedayGuideTemplate';
 public static readonly BASE_LIFEDAY_V1_REMOVE_LIFE_DAY: string = 'base-lifeday/base/lifeday/v1/removeLifeDay';
 public static readonly BASE_LIFEDAY_V1_SAVE_LIFE_DAY: string = 'base-lifeday/base/lifeday/v1/saveLifeDay';
 public static readonly BASE_LIFEDAY_V1_VIEW_RECIPROCAL: string = 'base-lifeday/base/lifeday/v1/view/reciprocal';
 public static readonly BASE_LIFEDAY_V2_GET_LIFE_DAY: string = 'base-lifeday/base/lifeday/v2/getLifeDay';
 public static readonly BASE_LIFEDAY_V2_VIEW_RECIPROCAL: string = 'base-lifeday/base/lifeday/v2/view/reciprocal';
 public static readonly CHECKALIVE: string = 'base-lifeday/checkalive';
}
