export class BasePayUrlConstant {
 public static readonly BASE_PAY_V1_HISTORY_DATA_COUNT: string = 'base-pay/base/pay/v1/historyDataCount';
 public static readonly BASE_PAY_V1_IAP_APPLE_PAY: string = 'base-pay/base/pay/v1/iap/applePay';
 public static readonly BASE_PAY_V1_IAP_ORDER_CREATE: string = 'base-pay/base/pay/v1/iap/order/create';
 public static readonly BASE_PAY_V1_ORDER_CREATE: string = 'base-pay/base/pay/v1/order/create';
 public static readonly BASE_PAY_V1_ORDER_LIST: string = 'base-pay/base/pay/v1/order/list';
 public static readonly BASE_PAY_V1_ORDER_PAY_CREATE: string = 'base-pay/base/pay/v1/order/pay/create';
 public static readonly BASE_PAY_V1_ORDER_QUERY: string = 'base-pay/base/pay/v1/order/query';
 public static readonly BASE_PAY_V1_ORDER_UPDATE_ORDER_STATE: string = 'base-pay/base/pay/v1/order/updateOrderState';
 public static readonly BASE_PAY_V1_PAY: string = 'base-pay/base/pay/v1/pay';
 public static readonly BASE_PAY_V1_REWARD_LIST: string = 'base-pay/base/pay/v1/rewardList';
 public static readonly CHECKALIVE: string = 'base-pay/checkalive';
}
