export class BaseThirdpartyUrlConstant {
 public static readonly BASE_THIRDPARTY_ACTIVITE_PUSH_DIRECT_REMIND: string = 'base-thirdparty/base/thirdparty/activitePushDirectRemind';
 public static readonly BASE_THIRDPARTY_INSERT_JG_REGISTER: string = 'base-thirdparty/base/thirdparty/insert/jg/register';
 public static readonly BASE_THIRDPARTY_PUSH_DIRECT_REMIND: string = 'base-thirdparty/base/thirdparty/pushDirectRemind';
 public static readonly BASE_THIRDPARTY_PUSH_REMIND: string = 'base-thirdparty/base/thirdparty/pushRemind';
 public static readonly BASE_THIRDPARTY_SEND_EMAIL_CODE: string = 'base-thirdparty/base/thirdparty/sendEmailCode';
 public static readonly BASE_THIRDPARTY_SEND_SMS_MESSAGE: string = 'base-thirdparty/base/thirdparty/sendSmsMessage';
 public static readonly BASE_THIRDPARTY_SEND_VOICE_MESSAGE: string = 'base-thirdparty/base/thirdparty/sendVoiceMessage';
 public static readonly BASE_THIRDPARTY_SENDEXPORTDATA: string = 'base-thirdparty/base/thirdparty/sendexportdata';
 public static readonly BASE_THIRDPARTY_SHORTURL: string = 'base-thirdparty/base/thirdparty/shorturl';
 public static readonly BASE_THIRDPARTY_SMS_REMIND: string = 'base-thirdparty/base/thirdparty/smsRemind';
 public static readonly BASE_THIRDPARTY_URL__KEY: string = 'base-thirdparty/base/thirdparty/url/{key}';
 public static readonly BASE_THIRDPARTY_V1_BAIDU_GET_OCR_TIMES: string = 'base-thirdparty/base/thirdparty/v1/baidu/getOcrTimes';
 public static readonly BASE_THIRDPARTY_V1_BAIDU_OCR: string = 'base-thirdparty/base/thirdparty/v1/baidu/ocr';
 public static readonly BASE_THIRDPARTY_V1_BAIDU_SPEECH_REC_GET_ACCESS_TOKEN: string = 'base-thirdparty/base/thirdparty/v1/baidu/speechRec/getAccessToken';
 public static readonly BASE_THIRDPARTY_VOICE_REMIND: string = 'base-thirdparty/base/thirdparty/voiceRemind';
 public static readonly BASE_THIRDPARTY_WX_REMIND: string = 'base-thirdparty/base/thirdparty/wxRemind';
 public static readonly BASE_THIRDPARTY_WX_REMIND_MONITOR: string = 'base-thirdparty/base/thirdparty/wxRemindMonitor';
 public static readonly CHECKALIVE: string = 'base-thirdparty/checkalive';
}
