export class ServiceTransferFutureUrlConstant {
 public static readonly CHECKALIVE: string = 'service-transfer-future/checkalive';
 public static readonly SERVICE_TRANSFER_V1_GET_SGX_USER_INFO: string = 'service-transfer-future/service/transfer/v1/getSgxUserInfo';
 public static readonly SERVICE_TRANSFER_V1_GET_TRANSFER_LIST: string = 'service-transfer-future/service/transfer/v1/getTransferList';
 public static readonly SERVICE_TRANSFER_V1_START_TRANSFER: string = 'service-transfer-future/service/transfer/v1/startTransfer';
 public static readonly SERVICE_TRANSFER_V2_GET_SGX_USER_INFO: string = 'service-transfer-future/service/transfer/v2/getSgxUserInfo';
 public static readonly SERVICE_TRANSFER_V2_GET_TRANSFER_LIST: string = 'service-transfer-future/service/transfer/v2/getTransferList';
 public static readonly SERVICE_TRANSFER_V2_START_TRANSFER: string = 'service-transfer-future/service/transfer/v2/startTransfer';
 public static readonly SERVICE_TRANSFER_V3_USER_TRANSFER_LOG: string = 'service-transfer-future/service/transfer/v3/userTransferLog';
}
