export class ServiceUserUrlConstant {
 public static readonly CHECKALIVE: string = 'service-user/checkalive';
 public static readonly SERVICE_USER_ACTIVITY_CREATE_PAY_ORDER: string = 'service-user/service/user/activity/createPayOrder';
 public static readonly SERVICE_USER_ACTIVITY_CREATE_PAY_ORDER4IOS: string = 'service-user/service/user/activity/createPayOrder4Ios';
 public static readonly SERVICE_USER_APPLET_LIST_URL: string = 'service-user/service/user/applet-list';
 public static readonly SERVICE_USER_APPLET_LIST_2_URL: string = 'service-user/service/user/applet-list-2';
 public static readonly SERVICE_USER_APPLET_LIST_NEW_URL: string = 'service-user/service/user/applet-list-new';
 public static readonly SERVICE_USER_CHECK_DEVICE_HEARTBEAT: string = 'service-user/service/user/checkDeviceHeartbeat';
 public static readonly SERVICE_USER_CLICK_APPLET_URL: string = 'service-user/service/user/click-applet';
 public static readonly SERVICE_USER_CREATE_ITEM_ORDER: string = 'service-user/service/user/createItemOrder';
 public static readonly SERVICE_USER_CREATE_PAY_ORDER: string = 'service-user/service/user/createPayOrder';
 public static readonly SERVICE_USER_CREATE_PAY_ORDER4IOS: string = 'service-user/service/user/createPayOrder4Ios';
 public static readonly SERVICE_USER_EVERYDAY_MOTTO_TEMPLATE_URL: string = 'service-user/service/user/everyday_motto_template';
 public static readonly SERVICE_USER_EVERYDAY_MOTTO_TEMPLATE_LIST_URL: string = 'service-user/service/user/everyday_motto_templateList';
 public static readonly SERVICE_USER_EVERYDAY_MOTTO_TEMPLATE_LIST_HOME_PAGE_URL: string = 'service-user/service/user/everyday_motto_templateListHomePage';
 public static readonly SERVICE_USER_EVERYDAY_MOTTO_TEMPLATE_PAGE_URL: string = 'service-user/service/user/everyday_motto_templatePage';
 public static readonly SERVICE_USER_GET_BUSINESS_SYNC_VERSION: string = 'service-user/service/user/getBusinessSyncVersion';
 public static readonly SERVICE_USER_INDEX_APPLET_LIST_URL: string = 'service-user/service/user/index-applet-list';
 public static readonly SERVICE_USER_INDEX_APPLET_LIST_2_URL: string = 'service-user/service/user/index-applet-list-2';
 public static readonly SERVICE_USER_INDEX_APPLET_LIST_NEW_URL: string = 'service-user/service/user/index-applet-list-new';
 public static readonly SERVICE_USER_SAVE_APPLET_LIST_URL: string = 'service-user/service/user/save-applet-list';
 public static readonly SERVICE_USER_SAVE_DEVICE_MSG_PUSH_INFO: string = 'service-user/service/user/saveDeviceMsgPushInfo';
 public static readonly SERVICE_USER_UPDATE_USER_INFO: string = 'service-user/service/user/updateUserInfo';
 public static readonly SERVICE_USER_V1_RED_PACKAGE_RECEIVE: string = 'service-user/service/user/v1/redPackage/receive';
 public static readonly SERVICE_USER_VIP_RESET_VIP_CONFIG: string = 'service-user/service/user/vip/resetVipConfig';
}
