export class ServiceWeixinUrlConstant {
 public static readonly CHECKALIVE: string = 'service-weixin/checkalive';
 public static readonly SERVICE_WEIXIN_ADD_PLAN_BY_TEXT: string = 'service-weixin/service/weixin/addPlanByText';
 public static readonly SERVICE_WEIXIN_API: string = 'service-weixin/service/weixin/api';
 public static readonly SERVICE_WEIXIN_DELETE_PLAN: string = 'service-weixin/service/weixin/deletePlan';
 public static readonly SERVICE_WEIXIN_GET_TOKEN: string = 'service-weixin/service/weixin/getToken';
 public static readonly SERVICE_WEIXIN_PARES_JS: string = 'service-weixin/service/weixin/paresJs';
 public static readonly SERVICE_WEIXIN_TEST: string = 'service-weixin/service/weixin/test';
}
