export class WebThirdpartyUrlConstant {
 public static readonly CHECKALIVE: string = 'web-thirdparty/checkalive';
 public static readonly WEB_THIRDPARTY_SEND_EMAIL_CODE: string = 'web-thirdparty/web/thirdparty/sendEmailCode';
 public static readonly WEB_THIRDPARTY_SEND_SMS_MESSAGE: string = 'web-thirdparty/web/thirdparty/sendSmsMessage';
 public static readonly WEB_THIRDPARTY_SEND_VOICE_MESSAGE: string = 'web-thirdparty/web/thirdparty/sendVoiceMessage';
 public static readonly WEB_THIRDPARTY_V1_RESET_SEND_EMAIL_CODE: string = 'web-thirdparty/web/thirdparty/v1/reset/sendEmailCode';
 public static readonly WEB_THIRDPARTY_V2_LOGGED_IN_SEND_SMS_MESSAGE: string = 'web-thirdparty/web/thirdparty/v2/loggedIn/sendSmsMessage';
}
